# Corvax-Frontier start
- type: antag
  id: Pirate
  name: roles-antag-pirate-name
  antagonist: true
  setPreference: true
  objective: ""
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 0 # test

- type: antag
  id: Firstmate
  name: roles-antag-firstmate-agent-name
  antagonist: true
  setPreference: true
  objective: ""
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 18000 # 5h

- type: antag
  id: PirateCaptain
  name: roles-antag-pirate-captain-name
  antagonist: true
  setPreference: true
  objective: ""
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 18000 # 5h
# Corvax-Frontier end

- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateCaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirate
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate
  innerClothingSkirt: ClothingUniformJumpskirtColorLightBrown
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateFirstmateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirateTricord
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    outerClothing: ClothingOuterCoatGentle
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled
